[nixpacks]
node-version = "18.20.5"

[variables]
NODE_VERSION = "18.20.5"
ENGINE_STRICT = "false"

[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
