[nixpacks]
node-version = "20.11.1"

[variables]
NODE_VERSION = "20.11.1"
ENGINE_STRICT = "false"

[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
