[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build:prod"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30

[variables]
NODE_VERSION = "23.11.0"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
