[build]
builder = "nixpacks"
buildCommand = "fnm install 23.11.0 && fnm use 23.11.0 && npm ci && npm run build:prod"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30

[nixpacks]
node_version = "23.11.0"

[variables]
NODE_VERSION = "23.11.0"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
ENGINE_STRICT = "false"
